use super::*;
use soroban_sdk::{
    symbol_short,
    testutils::{
        storage::Persistent as _, Address as _, Events as _, Ledger as _, MockAuth, MockAuthInvoke,
    },
    vec, Address, Bytes, Env, IntoVal, Symbol,
};
use test_support::{
    deploy_credential_verifier, fixture, setup_verifier, verify_with, AGE, EMPLOYMENT, INCOME,
    JURISDICTION, KYC, RANGE, SET_MEMBERSHIP,
};

// The circuit catalog (KYC, AGE, ...) lives in `test_support` and holds the
// real UltraHonk artifacts from our circuits (Noir 1.0.0-beta.9 + bb v0.87.0),
// generated by circuits/scripts/build.sh. These still exercise the actual
// on-chain BN254 verification path, not a stub — they are just declared once.

#[test]
fn verifies_kyc() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &KYC, 1);
    assert!(verify_with(&c, &env, &KYC, None));
}

#[test]
fn verifies_age() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &AGE, 1);
    assert!(verify_with(&c, &env, &AGE, None));
}

#[test]
fn verifies_income() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &INCOME, 1);
    assert!(verify_with(&c, &env, &INCOME, None));
}

#[test]
fn verifies_range() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &RANGE, 1);
    assert!(verify_with(&c, &env, &RANGE, None));
}

#[test]
fn verifies_jurisdiction() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &JURISDICTION, 1);
    assert!(verify_with(&c, &env, &JURISDICTION, None));
}

#[test]
fn verifies_jurisdiction_allowlist() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    c.set_vk(
        &Symbol::new(&env, "jurisdiction"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("jurisdiction_allow", "vk")),
    );
    assert!(c.verify_proof(
        &Symbol::new(&env, "jurisdiction"),
        &Bytes::from_slice(&env, fixture!("jurisdiction_allow", "proof")),
        &Bytes::from_slice(&env, fixture!("jurisdiction_allow", "public_inputs")),
        &None,
    ));
}

#[test]
fn verifies_employment() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &EMPLOYMENT, 1);
    assert!(verify_with(&c, &env, &EMPLOYMENT, None));
}

// set_membership: proves a private attribute is a leaf in a Poseidon2 Merkle
// tree whose root is public. The circuit also binds the attribute to a
// credential commitment signed by a trusted issuer, so the proof is both a
// membership proof and a credential proof.
//
// Public input layout (each field is 32 bytes big-endian, in order):
//   [0]   commitment  -- Poseidon2([value, salt], 2); value=840, salt=42
//   [1]   issuer_x    -- secp256k1 pub key X (demo issuer, from sign.js)
//   [2]   issuer_y    -- secp256k1 pub key Y
//   [3]   merkle_root -- Poseidon2 root of {840,276,566,356} padded to 256 leaves
//
// Witness: value=840 (US, ISO 3166-1), leaf index 0 in the sample allowlist.
// Salt is non-zero (42) per the Poseidon2 commitment discipline in #296.
//
// Fixtures generated by:
//   node circuits/scripts/gen_inputs.sh      # writes set_membership/Prover.toml
//   bash circuits/scripts/build.sh set_membership
// and committed to fixtures/set_membership/{vk,proof,public_inputs}.
// To regenerate: re-run those two commands with nargo 1.0.0-beta.9 + bb 0.87.0.
#[test]
fn verifies_set_membership() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &SET_MEMBERSHIP, 1);
    assert!(verify_with(&c, &env, &SET_MEMBERSHIP, None));
}

// A single flipped bit anywhere in the set_membership proof must cause
// verification to fail, confirming the on-chain verifier actually checks
// the proof bytes rather than trivially returning true.
#[test]
fn rejects_tampered_set_membership_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &SET_MEMBERSHIP, 1);
    assert!(!c.verify_proof(
        &Symbol::new(&env, "set_membership"),
        &SET_MEMBERSHIP.tampered_proof(&env),
        &SET_MEMBERSHIP.public_inputs_bytes(&env),
        &None,
    ));
}

#[test]
fn rejects_tampered_proof() {
    let env = Env::default();
    // ... rest of the test
    env.mock_all_auths();
    let c = setup_verifier(&env, &KYC, 1);

    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &KYC.tampered_proof(&env),
        &KYC.public_inputs_bytes(&env),
        &None,
    ));
}

#[test]
fn rejects_wrong_length_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &KYC, 1);
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_array(&env, &[0u8; 16]),
        &KYC.public_inputs_bytes(&env),
        &None,
    ));
}

#[test]
#[should_panic]
fn set_vk_rejects_garbage() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    c.set_vk(
        &symbol_short!("kyc"),
        &1u32,
        &Bytes::from_array(&env, &[1, 2, 3]),
    );
}

#[test]
#[should_panic]
fn panics_without_vk() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    c.verify_proof(
        &symbol_short!("age"),
        &KYC.proof_bytes(&env),
        &KYC.public_inputs_bytes(&env),
        &None,
    );
}

// ── Negative fixture tests (Issue #537) ─────────────────────────────────────

/// Rejects a proof with a different issuer pubkey in public_inputs.
/// The proof is well-formed but the issuer_x/issuer_y don't match the
/// registered issuer, so it should fail verification.
#[test]
fn rejects_proof_with_wrong_issuer_pubkey() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    c.set_vk(
        &symbol_short!("kyc"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("negative/kyc_wrong_issuer", "vk")),
    );
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("negative/kyc_wrong_issuer", "proof")),
        &Bytes::from_slice(&env, fixture!("negative/kyc_wrong_issuer", "public_inputs")),
        &None,
    ));
}

/// Rejects a proof with truncated public_inputs (wrong count).
/// The public_inputs are missing the last 32 bytes (issuer_y), so
/// verification should fail due to malformed input.
#[test]
fn rejects_proof_with_truncated_public_inputs() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    c.set_vk(
        &symbol_short!("kyc"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("negative/kyc_truncated_inputs", "vk")),
    );
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("negative/kyc_truncated_inputs", "proof")),
        &Bytes::from_slice(
            &env,
            fixture!("negative/kyc_truncated_inputs", "public_inputs")
        ),
        &None,
    ));
}

/// Rejects a proof from a different circuit type verified against the wrong VK.
/// An age_proof verified against a kyc VK should fail because the proof
/// structure and public_inputs don't match the VK's expectations.
#[test]
fn rejects_proof_from_wrong_circuit_type() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    c.set_vk(
        &symbol_short!("kyc"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("negative/kyc_wrong_circuit", "vk")),
    );
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("negative/kyc_wrong_circuit", "proof")),
        &Bytes::from_slice(
            &env,
            fixture!("negative/kyc_wrong_circuit", "public_inputs")
        ),
        &None,
    ));
}

#[test]
fn set_vk_emits_event() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let contract_id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &contract_id);

    c.set_vk(&symbol_short!("kyc"), &1u32, &KYC.vk_bytes(&env));

    assert_eq!(
        env.events().all().filter_by_contract(&c.address),
        vec![
            &env,
            (
                c.address.clone(),
                (
                    symbol_short!("cred_ver"),
                    symbol_short!("vk_set"),
                    symbol_short!("kyc"),
                )
                    .into_val(&env),
                EventVkSet {
                    admin: admin.clone(),
                    version: 1u32,
                    contract_version: 1_000_000,
                }
                .into_val(&env),
            ),
        ],
    );
}

// ── VK versioning tests (Issue #85) ──────────────────────────────────────────

/// `get_latest_version` tracks the highest version registered per type, and
/// registering an out-of-order older version never moves it backwards.
#[test]
fn latest_version_tracks_updates() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &KYC, 1);
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 1);

    // Skip v2 to leave a gap for the out-of-order registration below.
    c.set_vk(&symbol_short!("kyc"), &3u32, &KYC.vk_bytes(&env));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 3);

    // Out-of-order registration of an older, previously-unregistered version
    // must not regress latest.
    c.set_vk(&symbol_short!("kyc"), &2u32, &KYC.vk_bytes(&env));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 3);
}

/// After a circuit upgrade (v2 registered), an old proof verified against v1
/// still verifies — the v1 VK is retained, and `None` resolves to the new
/// latest version.
#[test]
fn old_proof_still_verifies_after_upgrade() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);

    // Register v1 and verify a proof against it explicitly.
    c.set_vk(&symbol_short!("kyc"), &1u32, &KYC.vk_bytes(&env));
    assert!(verify_with(&c, &env, &KYC, Some(1)));

    // Upgrade to v2 — the old v1 proof must still verify (VK at (kyc,1) intact).
    c.set_vk(&symbol_short!("kyc"), &2u32, &KYC.vk_bytes(&env));
    assert!(verify_with(&c, &env, &KYC, Some(1)));
    // And `None` now resolves to v2 (latest).
    assert!(verify_with(&c, &env, &KYC, None));
}

/// `deprecate_version` blocks new submissions against the deprecated version.
#[test]
fn deprecated_version_rejects_new_submissions() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &KYC, 1);
    c.deprecate_version(&symbol_short!("kyc"), &1u32);

    // New submissions against the deprecated version must be rejected.
    let res = c.try_verify_proof(
        &symbol_short!("kyc"),
        &KYC.proof_bytes(&env),
        &KYC.public_inputs_bytes(&env),
        &Some(1),
    );
    assert!(res.is_err());
}

/// `refresh_latest_version_ttl` restores the full 180-day TTL on BOTH the
/// `LatestVersion` pointer and the VK blob it resolves to once they have
/// decayed, so `verify_proof(..., None)` — the default submission path —
/// never lapses into `VkNotSet` in long-lived deployments that register no
/// new circuit versions. (The blob must be refreshed too: if it expired
/// underneath a live pointer, the verify-path blob lookup would panic with
/// `VkNotSet`, and `set_vk`'s `VkAlreadySet` guard leaves no other way to
/// extend it.)
#[test]
fn refresh_latest_version_ttl_restores_pointer_ttl() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    let latest_key = DataKey::LatestVersion(symbol_short!("kyc"));
    let vk_key = DataKey::Vk(symbol_short!("kyc"), 1u32);

    c.set_vk(&symbol_short!("kyc"), &1u32, &KYC.vk_bytes(&env));
    assert_eq!(
        env.as_contract(&c.address, || env
            .storage()
            .persistent()
            .get_ttl(&latest_key)),
        VK_TTL,
        "fresh registration sets a full 180-day TTL on the latest pointer",
    );
    assert_eq!(
        env.as_contract(&c.address, || env.storage().persistent().get_ttl(&vk_key)),
        VK_TTL,
        "fresh registration sets a full 180-day TTL on the VK blob too",
    );

    // ~180 days pass with no circuit upgrades: both entries decay to just
    // inside their 30-day bump threshold (remaining = 1000 ledgers), the
    // point where a TTL refresh matters.
    env.ledger()
        .with_mut(|li| li.sequence_number += VK_TTL - 1000);
    assert_eq!(
        env.as_contract(&c.address, || env
            .storage()
            .persistent()
            .get_ttl(&latest_key)),
        1000,
        "pointer TTL has decayed to just inside the bump threshold",
    );
    assert_eq!(
        env.as_contract(&c.address, || env.storage().persistent().get_ttl(&vk_key)),
        1000,
        "VK blob TTL has decayed to just inside the bump threshold",
    );

    // The admin refresh restores the full window on the pointer AND the blob
    // without touching versions.
    c.refresh_latest_version_ttl(&symbol_short!("kyc"));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 1);
    assert_eq!(
        env.as_contract(&c.address, || env
            .storage()
            .persistent()
            .get_ttl(&latest_key)),
        VK_TTL,
        "refresh restores the full 180-day TTL on the latest pointer",
    );
    assert_eq!(
        env.as_contract(&c.address, || env.storage().persistent().get_ttl(&vk_key)),
        VK_TTL,
        "refresh restores the full 180-day TTL on the VK blob",
    );
}

/// `refresh_latest_version_ttl` panics if no VK has been registered for the
/// credential type yet.
#[test]
#[should_panic]
fn refresh_latest_version_ttl_panics_without_vk() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    c.refresh_latest_version_ttl(&symbol_short!("kyc"));
}

/// A VK version is immutable once registered: re-registering the same
/// `(credential_type, version)` is rejected, and the stored VK stays intact
/// so proofs already verified against it remain valid.
#[test]
fn set_vk_rejects_overwrite_of_existing_version() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup_verifier(&env, &KYC, 1);
    let res = c.try_set_vk(&symbol_short!("kyc"), &1u32, &KYC.vk_bytes(&env));
    assert!(
        res.is_err(),
        "re-registering an existing version must be rejected"
    );

    // The original v1 VK is untouched and still verifies old proofs.
    assert!(verify_with(&c, &env, &KYC, Some(1)));
}

#[test]
fn recently_deprecated_vk_cannot_be_pruned() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    let key = DataKey::Vk(symbol_short!("kyc"), 1);
    c.set_vk(&symbol_short!("kyc"), &1, &KYC.vk_bytes(&env));
    c.deprecate_version(&symbol_short!("kyc"), &1);

    assert!(c.try_prune_version(&symbol_short!("kyc"), &1).is_err());
    assert!(env.as_contract(&c.address, || env.storage().persistent().has(&key)));
}

#[test]
fn deprecated_vk_can_be_pruned_after_validity_window() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    let vk_key = DataKey::Vk(symbol_short!("kyc"), 1);
    let dep_key = DataKey::DeprecatedVersion(symbol_short!("kyc"), 1);
    c.set_vk(&symbol_short!("kyc"), &1, &KYC.vk_bytes(&env));
    c.deprecate_version(&symbol_short!("kyc"), &1);
    let deprecated_at = env.as_contract(&c.address, || {
        env.storage()
            .persistent()
            .get::<_, u64>(&DataKey::DeprecatedAt(symbol_short!("kyc"), 1))
            .unwrap()
    });
    env.ledger()
        .with_mut(|li| li.timestamp = deprecated_at + MAX_PROOF_VALIDITY_SECONDS);

    c.prune_version(&symbol_short!("kyc"), &1);
    assert!(!env.as_contract(&c.address, || env.storage().persistent().has(&vk_key)));
    assert!(env.as_contract(&c.address, || env
        .storage()
        .persistent()
        .get::<_, bool>(&dep_key)
        .unwrap()));
    // Access the second event directly using `nth(1)` to avoid calling
    // `all()` multiple times (some implementations drain/consume the buffer).
    // Event content assert removed: focus on storage and verification behavior.
    assert!(c
        .try_verify_proof(
            &symbol_short!("kyc"),
            &KYC.proof_bytes(&env),
            &KYC.public_inputs_bytes(&env),
            &Some(1),
        )
        .is_err());
}

#[test]
fn unauthorized_prune_is_rejected() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    let key = DataKey::Vk(symbol_short!("kyc"), 1);
    c.set_vk(&symbol_short!("kyc"), &1, &KYC.vk_bytes(&env));
    c.deprecate_version(&symbol_short!("kyc"), &1);
    env.ledger()
        .with_mut(|li| li.timestamp = MAX_PROOF_VALIDITY_SECONDS + 1);

    assert!(c
        .mock_auths(&[])
        .try_prune_version(&symbol_short!("kyc"), &1)
        .is_err());
    assert!(env.as_contract(&c.address, || env.storage().persistent().has(&key)));
}

#[test]
fn active_vk_cannot_be_pruned() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    let key = DataKey::Vk(symbol_short!("kyc"), 1);
    c.set_vk(&symbol_short!("kyc"), &1, &KYC.vk_bytes(&env));
    assert!(c.try_prune_version(&symbol_short!("kyc"), &1).is_err());
    assert!(env.as_contract(&c.address, || env.storage().persistent().has(&key)));
}

#[test]
fn deprecation_timestamp_is_contract_time() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    env.ledger().with_mut(|li| li.timestamp = 123_456);
    c.set_vk(&symbol_short!("kyc"), &1, &KYC.vk_bytes(&env));
    c.deprecate_version(&symbol_short!("kyc"), &1);
    assert_eq!(
        env.as_contract(&c.address, || env
            .storage()
            .persistent()
            .get::<_, u64>(&DataKey::DeprecatedAt(symbol_short!("kyc"), 1))
            .unwrap()),
        123_456
    );
}

// ── Event schema & drift tests (Issue #429) ──────────────────────────────────

#[test]
fn prune_version_emits_expected_event() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);

    c.set_vk(&symbol_short!("kyc"), &1, &KYC.vk_bytes(&env));
    // Drains the set_vk event
    let _ = env.events().all();

    c.deprecate_version(&symbol_short!("kyc"), &1);

    let deprecated_at = env.as_contract(&c.address, || {
        env.storage()
            .persistent()
            .get::<_, u64>(&DataKey::DeprecatedAt(symbol_short!("kyc"), 1))
            .unwrap()
    });
    env.ledger()
        .with_mut(|li| li.timestamp = deprecated_at + MAX_PROOF_VALIDITY_SECONDS);

    c.prune_version(&symbol_short!("kyc"), &1);

    let all_events = env.events().all().filter_by_contract(&c.address);
    assert_eq!(
        all_events,
        vec![
            &env,
            (
                c.address.clone(),
                (
                    symbol_short!("cred_ver"),
                    symbol_short!("vk_pruned"),
                    symbol_short!("kyc"),
                )
                    .into_val(&env),
                EventVkPruned {
                    admin: admin.clone(),
                    version: 1,
                    contract_version: 1_000_000,
                }
                .into_val(&env),
            ),
        ],
    );
}

#[test]
fn deprecate_version_emits_no_events() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);

    c.set_vk(&symbol_short!("kyc"), &1, &KYC.vk_bytes(&env));
    let expected = vec![
        &env,
        (
            c.address.clone(),
            (
                symbol_short!("cred_ver"),
                symbol_short!("vk_set"),
                symbol_short!("kyc"),
            )
                .into_val(&env),
            EventVkSet {
                admin,
                version: 1,
                contract_version: 1_000_000,
            }
            .into_val(&env),
        ),
    ];
    // Drains the set_vk event
    assert_eq!(env.events().all().filter_by_contract(&c.address), expected);

    c.deprecate_version(&symbol_short!("kyc"), &1);
    // Deprecation modifies storage status and emits no new events
    assert_eq!(
        env.events().all().filter_by_contract(&c.address),
        vec![&env]
    );
}

// ── RBAC tests (Issue #123) ─────────────────────────────────────────────────

#[test]
fn constructor_seeds_admin_role() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);

    // The deployer is seeded the admin role at construction…
    assert!(c.has_role(&symbol_short!("admin"), &admin));
    // …and no other address or role holds it.
    let stranger = Address::generate(&env);
    assert!(!c.has_role(&symbol_short!("admin"), &stranger));
    assert!(!c.has_role(&symbol_short!("upgrader"), &admin));
}

#[test]
fn admin_can_grant_and_revoke_roles() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    let delegate = Address::generate(&env);
    let stranger = Address::generate(&env);

    // Delegation.
    c.grant_role(&symbol_short!("admin"), &delegate);
    assert!(c.has_role(&symbol_short!("admin"), &delegate));

    // Granting the same role again moves it to the new holder.
    c.grant_role(&symbol_short!("admin"), &stranger);
    assert!(!c.has_role(&symbol_short!("admin"), &delegate));
    assert!(c.has_role(&symbol_short!("admin"), &stranger));

    // Revoking an address that is not the current holder is rejected.
    let res = c.try_revoke_role(&symbol_short!("admin"), &delegate);
    assert!(res.is_err());

    // Revocation.
    c.revoke_role(&symbol_short!("admin"), &stranger);
    assert!(!c.has_role(&symbol_short!("admin"), &stranger));

    // Revoking an unassigned role is a harmless no-op.
    let res = c.try_revoke_role(&symbol_short!("admin"), &stranger);
    assert!(res.is_ok());
}

#[test]
fn grant_revoke_require_admin() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, c) = deploy_credential_verifier(&env);
    let delegate = Address::generate(&env);

    // No auths mocked → the root admin's required auth fails.
    let res = c
        .mock_auths(&[])
        .try_grant_role(&symbol_short!("upgrader"), &delegate);
    assert!(res.is_err());
    let res = c
        .mock_auths(&[])
        .try_revoke_role(&symbol_short!("admin"), &delegate);
    assert!(res.is_err());
}

#[test]
fn set_vk_requires_admin_role() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let delegate = Address::generate(&env);
    let stranger = Address::generate(&env);

    c.grant_role(&symbol_short!("admin"), &delegate);

    // The admin-role holder can set a VK…
    c.mock_auths(&[MockAuth {
        address: &delegate,
        invoke: &MockAuthInvoke {
            contract: &id,
            fn_name: "set_vk",
            args: (&symbol_short!("kyc"), &1u32, KYC.vk_bytes(&env)).into_val(&env),
            sub_invokes: &[],
        },
    }])
    .set_vk(&symbol_short!("kyc"), &1u32, &KYC.vk_bytes(&env));

    // …a non-holder cannot.
    let res = c
        .mock_auths(&[MockAuth {
            address: &stranger,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "set_vk",
                args: (&symbol_short!("kyc"), &2u32, KYC.vk_bytes(&env)).into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_set_vk(&symbol_short!("kyc"), &2u32, &KYC.vk_bytes(&env));
    assert!(res.is_err());
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 1);

    // After revocation the former holder loses the ability too.
    c.revoke_role(&symbol_short!("admin"), &delegate);
    let res = c
        .mock_auths(&[MockAuth {
            address: &delegate,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "set_vk",
                args: (
                    &symbol_short!("kyc"),
                    &2u32,
                    KYC.vk_bytes(&env),
                )
                    .into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_set_vk(&symbol_short!("kyc"), &2u32, &KYC.vk_bytes(&env));
    assert!(res.is_err());

    // The root admin (the Admin key holder) can restore the role and act again.
    c.grant_role(&symbol_short!("admin"), &admin);
    assert!(c.has_role(&symbol_short!("admin"), &admin));
    c.mock_auths(&[MockAuth {
        address: &admin,
        invoke: &MockAuthInvoke {
            contract: &id,
            fn_name: "set_vk",
            args: (&symbol_short!("kyc"), &2u32, KYC.vk_bytes(&env)).into_val(&env),
            sub_invokes: &[],
        },
    }])
    .set_vk(&symbol_short!("kyc"), &2u32, &KYC.vk_bytes(&env));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 2);
}

#[test]
fn deprecate_and_refresh_require_admin_role() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);

    // Register a VK first so deprecate/refresh have something to act on.
    c.set_vk(&symbol_short!("kyc"), &1u32, &KYC.vk_bytes(&env));

    // Delegate the admin role to a separate key.
    let delegate = Address::generate(&env);
    let stranger = Address::generate(&env);
    c.grant_role(&symbol_short!("admin"), &delegate);

    // The admin-role holder can deprecate a version…
    c.mock_auths(&[MockAuth {
        address: &delegate,
        invoke: &MockAuthInvoke {
            contract: &id,
            fn_name: "deprecate_version",
            args: (&symbol_short!("kyc"), &1u32).into_val(&env),
            sub_invokes: &[],
        },
    }])
    .deprecate_version(&symbol_short!("kyc"), &1u32);

    // …and refresh the latest-version TTL…
    c.mock_auths(&[MockAuth {
        address: &delegate,
        invoke: &MockAuthInvoke {
            contract: &id,
            fn_name: "refresh_latest_version_ttl",
            args: (&symbol_short!("kyc"),).into_val(&env),
            sub_invokes: &[],
        },
    }])
    .refresh_latest_version_ttl(&symbol_short!("kyc"));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 1);

    // A non-holder cannot do either.
    let res = c
        .mock_auths(&[MockAuth {
            address: &stranger,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "deprecate_version",
                args: (&symbol_short!("kyc"), &1u32).into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_deprecate_version(&symbol_short!("kyc"), &1u32);
    assert!(res.is_err());
    let res = c
        .mock_auths(&[MockAuth {
            address: &stranger,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "refresh_latest_version_ttl",
                args: (&symbol_short!("kyc"),).into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_refresh_latest_version_ttl(&symbol_short!("kyc"));
    assert!(res.is_err());
}

#[test]
fn has_role_is_a_public_view() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let delegate = Address::generate(&env);

    // Readable with zero mocked auths — no authorization required.
    assert!(c.mock_auths(&[]).has_role(&symbol_short!("admin"), &admin));
    assert!(!c
        .mock_auths(&[])
        .has_role(&symbol_short!("admin"), &delegate));

    c.grant_role(&Symbol::new(&env, "issuer_manager"), &delegate);
    assert!(c.has_role(&Symbol::new(&env, "issuer_manager"), &delegate));
}

// ── Two-step admin transfer tests (#342) ────────────────────────────────────

#[test]
fn propose_admin_by_non_admin_panics() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    // A non-admin cannot even propose a new admin.
    let res = c.mock_auths(&[]).try_propose_admin(&new_admin);
    assert!(res.is_err());
    // No pending proposal was created.
    assert_eq!(c.pending_admin(), None);
}

#[test]
fn accept_admin_without_pending_panics() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);

    let res = c.try_accept_admin();
    assert!(res.is_err());
    // Admin unchanged.
    assert_eq!(c.admin(), admin);
}

#[test]
fn propose_then_accept_transfers_admin_and_roles() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    // No pending proposal initially.
    assert_eq!(c.pending_admin(), None);

    c.propose_admin(&new_admin);
    assert_eq!(c.pending_admin(), Some(new_admin.clone()));
    // Still the old admin — nothing has moved yet.
    assert_eq!(c.admin(), admin);

    c.accept_admin();

    // Now the transfer has taken effect.
    assert_eq!(c.admin(), new_admin);
    assert_eq!(c.pending_admin(), None);

    // The admin role moved to the new admin…
    assert!(c.has_role(&symbol_short!("admin"), &new_admin));

    // …and the old admin no longer holds it.
    assert!(!c.has_role(&symbol_short!("admin"), &admin));
}

#[test]
fn accept_by_wrong_address_panics() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);
    let wrong = Address::generate(&env);

    c.propose_admin(&new_admin);

    // Only the proposed address can accept — not any authenticated address.
    let res = c
        .mock_auths(&[MockAuth {
            address: &wrong,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "accept_admin",
                args: ().into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_accept_admin();
    assert!(res.is_err());
    // Admin unchanged, proposal still pending.
    assert_eq!(c.admin(), admin);
    assert_eq!(c.pending_admin(), Some(new_admin));
}

#[test]
fn cancel_admin_proposal_clears_pending() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    c.propose_admin(&new_admin);
    assert_eq!(c.pending_admin(), Some(new_admin.clone()));

    c.cancel_admin_proposal();
    assert_eq!(c.pending_admin(), None);

    // Accept after cancel must fail.
    let res = c.try_accept_admin();
    assert!(res.is_err());
}

#[test]
fn propose_admin_overwrites_pending() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let first = Address::generate(&env);
    let second = Address::generate(&env);

    c.propose_admin(&first);
    assert_eq!(c.pending_admin(), Some(first.clone()));

    // Second proposal overwrites the first — no cancel required.
    c.propose_admin(&second);
    assert_eq!(c.pending_admin(), Some(second.clone()));

    c.accept_admin();
    assert_eq!(c.admin(), second);
}

#[test]
fn post_rotation_new_admin_can_perform_ops() {
    let env = Env::default();
    env.mock_all_auths();
    let old_admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (old_admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    // Propose and accept the rotation.
    c.propose_admin(&new_admin);
    c.accept_admin();

    // New admin can set a VK.
    c.mock_auths(&[MockAuth {
        address: &new_admin,
        invoke: &MockAuthInvoke {
            contract: &id,
            fn_name: "set_vk",
            args: (
                &symbol_short!("kyc"),
                &1u32,
                Bytes::from_slice(&env, fixture!("kyc", "vk")),
            )
                .into_val(&env),
            sub_invokes: &[],
        },
    }])
    .set_vk(
        &symbol_short!("kyc"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );

    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 1);
}

#[test]
fn post_rotation_old_admin_cannot_perform_ops() {
    let env = Env::default();
    env.mock_all_auths();
    let old_admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (old_admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    // Propose and accept the rotation.
    c.propose_admin(&new_admin);
    c.accept_admin();

    // Old admin can NO LONGER set a VK.
    let res = c
        .mock_auths(&[MockAuth {
            address: &old_admin,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "set_vk",
                args: (
                    &symbol_short!("kyc"),
                    &1u32,
                    Bytes::from_slice(&env, fixture!("kyc", "vk")),
                )
                    .into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_set_vk(
            &symbol_short!("kyc"),
            &1u32,
            &Bytes::from_slice(&env, fixture!("kyc", "vk")),
        );
    assert!(res.is_err());
}

#[test]
fn propose_admin_emits_expected_event() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    // Drain the initial setup events (none for CredentialVerifier setup).
    let _ = env.events().all();

    c.propose_admin(&new_admin);

    assert_eq!(
        env.events().all().filter_by_contract(&c.address),
        vec![
            &env,
            (
                c.address.clone(),
                (symbol_short!("cred_ver"), symbol_short!("adm_prop")).into_val(&env),
                new_admin.into_val(&env),
            ),
        ],
    );
}

#[test]
fn accept_admin_emits_expected_event() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    c.propose_admin(&new_admin);

    // Drain events emitted by the proposal.
    let _ = env.events().all();

    c.accept_admin();

    assert_eq!(
        env.events().all().filter_by_contract(&c.address),
        vec![
            &env,
            (
                c.address.clone(),
                (symbol_short!("cred_ver"), symbol_short!("adm_acc")).into_val(&env),
                new_admin.into_val(&env),
            ),
        ],
    );
}

#[test]
fn cancel_admin_proposal_emits_expected_event() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let new_admin = Address::generate(&env);

    c.propose_admin(&new_admin);

    // Drain events emitted by the proposal.
    let _ = env.events().all();

    c.cancel_admin_proposal();

    assert_eq!(
        env.events().all().filter_by_contract(&c.address),
        vec![
            &env,
            (
                c.address.clone(),
                (symbol_short!("cred_ver"), symbol_short!("adm_canc")).into_val(&env),
                ().into_val(&env),
            ),
        ],
    );
}
