#![cfg(test)]

use super::*;
use soroban_sdk::{symbol_short, testutils::Address as _, Address, Bytes, Env, Symbol};

// Real UltraHonk artifacts from our circuits (Noir 1.0.0-beta.9 + bb v0.87.0),
// generated by circuits/scripts/build.sh. These exercise the actual on-chain
// BN254 verification path, not a stub.
macro_rules! fixture {
    ($t:literal, $f:literal) => {
        include_bytes!(concat!("../../../fixtures/", $t, "/", $f))
    };
}

fn setup(env: &Env) -> CredentialVerifierClient<'_> {
    let admin = Address::generate(env);
    let id = env.register(CredentialVerifier, (admin,));
    CredentialVerifierClient::new(env, &id)
}

#[test]
fn verifies_kyc() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    ));
}

#[test]
fn verifies_age() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("age"), &Bytes::from_slice(&env, fixture!("age", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("age"),
        &Bytes::from_slice(&env, fixture!("age", "proof")),
        &Bytes::from_slice(&env, fixture!("age", "public_inputs")),
    ));
}

#[test]
fn verifies_income() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("income"), &Bytes::from_slice(&env, fixture!("income", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("income"),
        &Bytes::from_slice(&env, fixture!("income", "proof")),
        &Bytes::from_slice(&env, fixture!("income", "public_inputs")),
    ));
}

#[test]
fn verifies_jurisdiction() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &Symbol::new(&env, "jurisdiction"),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "vk")),
    );
    assert!(c.verify_proof(
        &Symbol::new(&env, "jurisdiction"),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "proof")),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "public_inputs")),
    ));
}

#[test]
fn rejects_tampered_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &Bytes::from_slice(&env, fixture!("kyc", "vk")));

    let mut bad = fixture!("kyc", "proof").to_vec();
    bad[5000] ^= 0xff;
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, &bad),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    ));
}

#[test]
fn rejects_wrong_length_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_array(&env, &[0u8; 16]),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    ));
}

#[test]
#[should_panic]
fn set_vk_rejects_garbage() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &Bytes::from_array(&env, &[1, 2, 3]));
}

#[test]
#[should_panic]
fn panics_without_vk() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.verify_proof(
        &symbol_short!("age"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    );
}
