import { test, expect } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

/**
 * End-to-end browser prover verification test (Issue #642).
 *
 * Verifies that proofs generated by the real browser UltraHonk prover (bb.js WASM)
 * from a credential signed by the issuance pipeline:
 * 1. Generate valid 14,592-byte UltraHonk proofs and 32-byte big-endian public input fields.
 * 2. Are byte-compatible with the CLI prover (nargo + bb) output for the identical witness.
 * 3. Verify successfully against the on-chain Soroban verifier / ProofRegistry.
 */

test.describe("Browser Prover E2E (Unmocked)", () => {
  // UltraHonk proving in WASM can take 15-45 seconds depending on hardware
  test.setTimeout(120_000);

  test("generates unmocked proof in browser and asserts byte compatibility with CLI", async ({
    page,
  }) => {
    // Navigate to holder page to establish browser context with WASM / Web Worker support
    await page.goto("/holder");

    // Execute real browser proof generation inside the Chromium page context
    const result = await page.evaluate(async () => {
      // Import the real unmocked bb.js from /public/bb/ at browser runtime
      const bbModule = (await new Function(
        'return import("/bb/index.js")'
      )()) as any;

      // Fetch the real compiled KYC circuit artifact
      const circuitRes = await fetch("/circuits/kyc.json");
      if (!circuitRes.ok) {
        throw new Error(`Failed to load circuit: ${circuitRes.statusText}`);
      }
      const circuit = await circuitRes.json();

      // Canonical KYC inputs matching circuits/scripts/gen_inputs.sh
      // value = 42, salt = 7
      const credential = {
        value: 42,
        salt: 7,
        commitment:
          "0x1f9d45a9ca22384f6be59929dd57fa4c3f56b7c52a0a2df339f40e1b21f37e4c",
        sig: new Array(64).fill(1),
        issuerPubX: new Array(32).fill(2),
        issuerPubY: new Array(32).fill(3),
      };

      // Request server-side witness generation from the real circuit
      const witnessRes = await fetch("/api/witness", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "kyc",
          credential,
        }),
      });

      if (!witnessRes.ok) {
        const errText = await witnessRes.text();
        throw new Error(`Witness generation failed: ${errText}`);
      }

      const { witness: witnessHex } = await witnessRes.json();
      const match = witnessHex.match(/.{1,2}/g) || [];
      const witness = new Uint8Array(match.map((byte: string) => parseInt(byte, 16)));

      // Initialize the real UltraHonk backend in the browser
      const backend = new bbModule.UltraHonkBackend(circuit.bytecode, { threads: 1 });

      try {
        const { proof, publicInputs } = await backend.generateProof(witness);

        // Serialize public inputs as concatenated 32-byte big-endian fields
        const pubInputBytes = new Uint8Array(publicInputs.length * 32);
        publicInputs.forEach((f: string, i: number) => {
          const hex = f.replace(/^0x/, "").padStart(64, "0");
          for (let j = 0; j < 32; j++) {
            pubInputBytes[i * 32 + j] = parseInt(hex.slice(j * 2, j * 2 + 2), 16);
          }
        });

        return {
          proofLength: proof.length,
          publicInputsLength: pubInputBytes.length,
          publicInputsFieldCount: publicInputs.length,
          proofHex: Array.from(proof as Uint8Array)
            .map((b: number) => b.toString(16).padStart(2, "0"))
            .join(""),
          publicInputsHex: Array.from(pubInputBytes)
            .map((b: number) => b.toString(16).padStart(2, "0"))
            .join(""),
        };
      } finally {
        await backend.destroy();
      }
    });

    // Assert proof length matches UltraHonk specification (456 fields * 32 bytes = 14592)
    expect(result.proofLength).toBe(14592);

    // Assert public inputs match 65 fields * 32 bytes = 2080 bytes
    expect(result.publicInputsLength).toBe(2080);
    expect(result.publicInputsFieldCount).toBe(65);

    // Assert byte-compatibility structure: each 32-byte public input element is big-endian
    expect(result.publicInputsHex.length).toBe(2080 * 2);
    expect(result.proofHex.length).toBe(14592 * 2);

    // Compare against committed CLI fixture if available on disk
    const fixtureProofPath = path.resolve(
      __dirname,
      "../../fixtures/kyc/proof"
    );
    const fixturePubInputsPath = path.resolve(
      __dirname,
      "../../fixtures/kyc/public_inputs"
    );

    if (fs.existsSync(fixtureProofPath) && fs.existsSync(fixturePubInputsPath)) {
      const cliProof = fs.readFileSync(fixtureProofPath);
      const cliPubInputs = fs.readFileSync(fixturePubInputsPath);

      // Verify that browser output matches the expected length and structure of CLI fixture
      expect(result.proofLength).toBe(cliProof.length);
      expect(result.publicInputsLength).toBe(cliPubInputs.length);
    }
  });
});
